version: '3.4'

services:
  ge_chatapp:
    image: ${DOCKER_REGISTRY-}gechatapp
    build:
      context: .
      dockerfile: GE_Chatapp/GE_Chatapp/Dockerfile
    ports: 
      - 8080:8080
       
  postgres:
    image: postgres:latest
    container_name: chat_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password!
    volumes:
      - chat_db_data:/var/lib/postgresql/data
      - ../chatdb/init-scripts:/docker-entrypoint-initdb.d