version: '3.4'

services:
  ge_chatapp:
    image: ${DOCKER_REGISTRY-}gechatapp
    container_name: ge_chatapp
    build:
      context: .
      dockerfile: GE_Chatapp/GE_Chatapp/Dockerfile
    ports: 
      - 8080:8080
      - 80801:8081
    environment:
      - DOTNET_URLS=http://+:5000 # by default Dotnet only listens to requests coming from 'localhost' from within the container, adding this will listen outside
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chatdb;Username=admin;Password=password!
  
  postgres:
    image: postgres:latest
    container_name: chat_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password!
    volumes:
      - chat_db_data:/var/lib/postgresql/data
      - ../chatdb/init-scripts:/docker-entrypoint-initdb.d
volumes:
  chat_db_data:
