version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: GE-chat-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/garrett/chatdata/data:/var/lib/postgresql/data
      - ../chatdb/init-scripts:/docker-entrypoint-initdb.d
    restart: always
     
  chatapp:
    container_name: GE_chatapp
    build:
      context: ../../
      dockerfile: GE_Chatapp/GE_Chatapp/Dockerfile

    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ApiBaseAddress=http://chatapp:8080/api
    restart: always 

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=gechatapp.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/garrett/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:1360:443
    restart: always