{
 "title": "Image Information",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Message With Image vs Without",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(messages_count_total{job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(message_with_image_total{job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Containing Images",
   "type": "traces",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "ac436ac7f67f2a5bdaa592231020f99f"
    }
   ]
  },
  {
   "title": "Request/Response Times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{http_route=\"api/Chat\", job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}