name: Deploy Application

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
  GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs: 
    
  format: 
    uses: ./.github/workflows/format.yml
    
  unit-tests:
    needs: format  
    uses: ./.github/workflows/unit-test.yml
  
  integration-tests: 
    needs: format
    uses: ./.github/workflows/integration-test.yml

  deploy:
    needs: [unit-tests, integration-tests]
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: redeploy application
        run: |
          cd ops/deployment
          docker compose pull
          docker compose build
          docker compose up -d