name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    integration-tests:
        runs-on: [self-hosted]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: "8.0"

        - name: Run Tests in using Docker test containers
          run: |
           dotnet test

