name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    unit-tests:
        runs-on: [self-hosted]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3

        - name: Run Tests in using Docker test containers
          run: |
           cd ./Integration_Test
           dotnet test

