name: Run Unit Tests
on: [push]

jobs: 
    dotnet-format:
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Dotnet
            uses: actions/setup-dotnet@v2
            with:
              dotnet-version: "8.0"
          - name: Format
            run: dotnet format ./GE_Chatapp.sln --verify-no-changes --verbosity diagnostic

    unit-tests:
        needs: dotnet-format
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Dotnet
            uses: actions/setup-dotnet@v2
            with:
              dotnet-version: "8.0"
          
          - name: Restore dependencies and Run tests
            run: |
              cd Unit_Test/
              dotnet test