name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    unit-tests:
        runs-on: [self-hosted]
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Tests in Docker
          run: |
              docker build -t chat_test -f ./ops/tests/Dockerfile .
              docker run -i --rm chat_test dotnet test ./GE_Chatapp.sln
