name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    unit-tests:
        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build Docker Image
          run: docker build -t chat_tests -f ./Unit_Test/Dockerfile .
        - name: Run Tests in Docker
          run: |
            docker run --name chat_tests_container chat_tests dotnet test
            exit_code=$?
            echo "Test exit code: $exit_code"
            exit $exit_code
        - name: Cleanup Docker Container
          if: always() # This ensures the cleanup step runs whether the previous step passes or fails
          run: docker rm -f chat_tests_container || true