name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    unit-tests:
        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build Docker Image
          run: docker build -t chat_tests -f ./Unit_Test/Dockerfile .

        - name: Run Tests in Docker
          run: |
              pwd
              docker run -t --rm chat_tests dotnet test ../Unit_Test --verbosity normal