name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
    unit-tests:
        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Restore dependencies and run tests
          run: |
            docker build -t chat_tests_container -f ./Unit_Test/Dockerfile .
            docker run -d --name chat_tests_container chat_tests tail -f /dev/null
            docker exec chat_tests_container dotnet test
            docker rm -f chat_tests_container